### ISSUE TITLE
 what is meta.pickle

### ISSUE THREAD

**Issue by lz666win** [goddoe/weakly-supervised-detector#1]
I run snippet-train.py,I think you maybe change the name so I change as
meta_path = "{}/data/tiny_imagenet_200/pickle/tiny_imagenet.pickle".format(project_path)
but it still problem:
clf_var_to_optimize_list
[<tf.Variable 'clf/conv/weights:0' shape=(3, 3, 2048, 1024) dtype=float32_ref>,
 <tf.Variable 'clf/conv/BatchNorm/beta:0' shape=(1024,) dtype=float32_ref>,
 <tf.Variable 'clf/conv/BatchNorm/moving_mean:0' shape=(1024,) dtype=float32_ref>,
 <tf.Variable 'clf/conv/BatchNorm/moving_variance:0' shape=(1024,) dtype=float32_ref>,
 <tf.Variable 'clf/logits/weights:0' shape=(1, 1, 1024, 200) dtype=float32_ref>,
 <tf.Variable 'clf/logits/biases:0' shape=(200,) dtype=float32_ref>]
2018-09-03 22:14:25.058164: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:/Users/lz666/PycharmProjects/weakly-supervised-detector-1/snippet_train_model.py", line 59, in <module>
    d['init_dataset_train_has'],
KeyError: 'init_dataset_train_has'
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
I'm dead
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
I do not know what happened,where is 'init_dataset_train_has' defined?

**Comment by goddoe** [comment]
Hello @lz666win, thanks for reporting.

init_dataset_train_has is related to [hide-and-seek](
https://github.com/goddoe/hide-and-seek)
There are some history.  At first time, I made three different models which related to weakly supervised model at same private repo and split each models and then uploaded them public. 
But I didn't check them working after splitting. 

I'll fix them soon and let you know it done.

**Comment by goddoe** [comment]
Hi again, @lz666win
I fixed the issue that you reported. However, The codes are too old for now and there are many things that needed to be refactored or update. Therefore, I'll continue update my codes. thanks!

**Comment by lz666win** [comment]
@goddoe,sorry to bother you again
I use your new code,the meta.pickle appear,but the problem 'KeyError: 'init_dataset_train_has' 'is still happened,I notice this related to another of you repository.I want to know is anything wrong with my order?I run data_download.py first,then run snippet-train.py, did any code I should run in middle?

**Comment by goddoe** [comment]
@lz666win , 
I'm appreciated for your reporting. I fixed snippet_train_model.py
May be it will work.

Yes, the order of the training is 
1. download_data.py
2. train.ipynb or snippt_train_model.py

For evaluation, use load_and_test.ipynb.

thanks!

**Comment by lz666win** [comment]
sorry to bother you again, with7 days training(I use cpu),I got a checkpoint"vanili_incept_v3",but when I use  load_and_test.ipynb to evaluate, I found load_and_test.ipynb also need to fix .Some function like load_data_with_meta has been removed from helpers.py, and some other files'name has been changed.Do you have time to fix it?
Thank you!

**Comment by goddoe** [comment]
@lz666win 
Sorry for late response. Sorry again, I'm so busy these days so, I think I can't fix it soon. 

'load_data_with_meta' is same with the function 'load_from_pickle' in ./libs/various_utils module.
If there are 'load_data_with_meta', please replace it with 'load_from_pickle'

load_from_picke is like below.
```
def load_from_pickle(path):
    with open(path, "rb") as f:
        return pickle.load(f) 
```

Thanks.
